# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{allocine}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jordan Bracco", "Florian Lamache", "Sunny Ripert"]
  s.date = %q{2009-11-19}
  s.description = %q{Get data about movies and shows on allocine.fr}
  s.email = %q{jordan@bracco.name}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "allocine.gemspec",
     "lib/allocine.rb",
     "lib/allocine/movie.rb",
     "lib/allocine/show.rb",
     "lib/allocine/web.rb",
     "lib/allocine/web/curb.rb",
     "lib/allocine/web/open_uri.rb",
     "spec/allocine_spec.rb",
     "spec/helper.rb",
     "spec/movie_spec.rb",
     "spec/show_spec.rb"
  ]
  s.homepage = %q{http://github.com/webs/allocine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{allocine}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Parser for Allocine.fr}
  s.test_files = [
    "spec/allocine_spec.rb",
     "spec/helper.rb",
     "spec/movie_spec.rb",
     "spec/show_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["> 0.0.0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["> 0.0.0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["> 0.0.0"])
  end
end

